// src/store/actions/types.js

export const FETCH_ALLTHEMES_SUCCESS = 'FETCH_ALLTHEMES_SUCCESS';
export const FETCH_THEME_SUCCESS = 'FETCH_THEME_SUCCESS';
export const FETCH_WORDSLIST_SUCCESS = 'FETCH_WORDSLIST_SUCCESS';
