// src/store/actions/types.js

export const FETCH_ALLTHEMES_SUCCESS = 'FETCH_ALLTHEMES_SUCCESS';
export const FETCH_THEME_SUCCESS = 'FETCH_THEME_SUCCESS';
export const SET_SELECTED_THEME = 'SET_SELECTED_THEME';
export const SET_WORD_INDEX = 'SET_WORD_INDEX';


