spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    import:
      - classpath:/application-db.yml
      - classpath:/application-jwt.yml
      - classpath:/application-redis.yml
      - classpath:/application-s3.yml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

OPENVIDU_URL: http://i9E206.p.ssafy.io:5443/
OPENVIDU_SECRET: ssafy




server:
  port: 8080
  ssl:
    enabled: false

