spring:
  config:
    import:
      - classpath:/application-db.yml
      - classpath:/application-redis.yml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

OPENVIDU_URL: http://i9E206.p.ssafy.io:5443/
OPENVIDU_SECRET: ssafy

server:
  port: 8080
  ssl:
    enabled: false

